name: Deploy CiLearn
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-job
        uses: nekiro/ssh-job@v1.0.5
        with:
          host: "tombeev2.beget.tech"
          user: "tombeev2"
          password: "#jey&32%fr"
          command: |
            spawn ssh tombeev2@tombeev2.beget.tech
            expect "password:"
            send "#jey&32%fr\r"
