name: Deploy CiLearn
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Run a one-line script
        run: |
          set timeout 1
          spawn ssh tombeev2@tombeev2.beget.tech
          expect "password:"
          send "#jey&32%fr\r";
          expect eof
