name: Deploy CiLearn
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-job
        uses: nekiro/ssh-job@v1.0.5
        with:
          host: "tombeev2.beget.tech"
          port: 222
          user: "tombeev2"
          password: "#jey&32%fr"
          command: |
            ssh localhost -p 222
            #jey&32%fr
